// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.ClearPeerAppData~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.ClearRoomAppData(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.CloseConsumer(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.CloseProducer(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.ConnectWebRtcTransport(TubumuMeeting.Mediasoup.ConnectWebRtcTransportRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.CreateConsumer(TubumuMeeting.Meeting.Server.Peer,TubumuMeeting.Meeting.Server.Peer,TubumuMeeting.Mediasoup.Producer,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.CreateWebRtcTransport(TubumuMeeting.Mediasoup.CreateWebRtcTransportRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.GetConsumerStats(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.GetProducerStats(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.GetTransportStats(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.Join(TubumuMeeting.Mediasoup.JoinRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.JoinRoom(TubumuMeeting.Mediasoup.JoinRoomRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.LeaveRoom(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.PauseConsumer(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.PauseProducer(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.Produce(TubumuMeeting.Mediasoup.ProduceRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.Pull(TubumuMeeting.Mediasoup.PullRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.RequestConsumerKeyFrame(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.RestartIce(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.ResumeConsumer(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.ResumeProducer(System.String)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.SendMessage(TubumuMeeting.Mediasoup.SendMessageRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.SetConsumerPreferedLayers(TubumuMeeting.Mediasoup.SetConsumerPreferedLayersRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.SetConsumerPriority(TubumuMeeting.Mediasoup.SetConsumerPriorityRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.SetPeerAppData(TubumuMeeting.Mediasoup.SetPeerAppDataRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.SetRoomAppData(TubumuMeeting.Mediasoup.SetRoomAppDataRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.UnsetPeerAppData(TubumuMeeting.Mediasoup.UnsetPeerAppDataRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
[assembly: SuppressMessage("Build", "VSTHRD200:如果方法返回可等待的类型，则在其名称中使用 “Async” 语法。", Justification = "<挂起>", Scope = "member", Target = "~M:TubumuMeeting.Meeting.Server.MeetingHub.UnsetRoomAppData(TubumuMeeting.Mediasoup.UnsetRoomAppDataRequest)~System.Threading.Tasks.Task{TubumuMeeting.Meeting.Server.MeetingMessage}")]
